/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedVisitsRouteImport } from './routes/_authenticated/visits'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads/index'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads/$leadId'
import { Route as AuthenticatedLeadsNewRouteImport } from './routes/_authenticated/leads/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsRoute = AuthenticatedVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsNewRoute = AuthenticatedLeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/leads/new': typeof AuthenticatedLeadsNewRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/leads/new': typeof AuthenticatedLeadsNewRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/visits': typeof AuthenticatedVisitsRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/leads/new': typeof AuthenticatedLeadsNewRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/bookings'
    | '/dashboard'
    | '/followups'
    | '/reports'
    | '/visits'
    | '/leads/$leadId'
    | '/leads/new'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/bookings'
    | '/dashboard'
    | '/followups'
    | '/reports'
    | '/visits'
    | '/leads/$leadId'
    | '/leads/new'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/bookings'
    | '/_authenticated/dashboard'
    | '/_authenticated/followups'
    | '/_authenticated/reports'
    | '/_authenticated/visits'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/leads/new'
    | '/_authenticated/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits': {
      id: '/_authenticated/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AuthenticatedVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/new': {
      id: '/_authenticated/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof AuthenticatedLeadsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedVisitsRoute: typeof AuthenticatedVisitsRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedLeadsNewRoute: typeof AuthenticatedLeadsNewRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedVisitsRoute: AuthenticatedVisitsRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedLeadsNewRoute: AuthenticatedLeadsNewRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
